server:
  port: 8882
  servlet:
    context-path: /
logging:
  level:
    org.sc: debug

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


