/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sc_DemoJni */

#ifndef _Included_org_sc_DemoJni
#define _Included_org_sc_DemoJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sc_DemoJni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_sc_DemoJni_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
